apiVersion: v1
kind: Service
metadata:
  name: sample-go-service
  namespace: sample-apps
  labels:
    app: sample-go
spec:
  selector:
    app: sample-go
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
